[net]
git-fetch-with-cli = true

# For Linux
# https://stackoverflow.com/questions/67511990/how-to-use-the-mold-linker-with-cargo
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld"]